version: '3'

services:
  protonmail-bridge:
    container_name: protonmail-bridge
    build: ./deb
    user: "8535:8535"
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    volumes:
      - protonmail:/home/protonmail
    restart: unless-stopped
    stdin_open: true 
    tty: true
